<?php
/*
 * This file has been automatically generated by TDBM.
 * You can edit this file as it will not be overwritten.
 */

declare(strict_types=1);

namespace core\Daos;

use core\Daos\Generated\AbstractBalancerDao;

/**
 * The BalancerDao class will maintain the persistence of Balancer class into the balancers table.
 */
class BalancerDao extends AbstractBalancerDao
{
}
